version: '3.8'
services:
  app:
    container_name: app_node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - dev-pg
    volumes:
      - .:/app

  dev-pg:
    image: postgres:13
    container_name: db_pg
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    